import{a as E,S as v,i as s}from"./assets/vendor-CDCTPtxx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function u(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const B="52850733-d97c0fbc64eee6c455900e64a",I="https://pixabay.com/api/";async function f(o,e=1){try{return(await E.get(I,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(t){throw console.error("Pixabay API error:",t),t}}const m=document.querySelector(".gallery"),P=new v(".gallery a"),h=document.getElementById("loader"),y=document.getElementById("load-more");function g(o){const e=o.map(t=>`
        <li class="gallery-item">
          <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${t.likes}</p>
            <p><b>Views:</b> ${t.views}</p>
            <p><b>Comments:</b> ${t.comments}</p>
            <p><b>Downloads:</b> ${t.downloads}</p>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",e),P.refresh()}function S(){m.innerHTML=""}function p(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function L(){y.classList.remove("hidden")}function a(){y.classList.add("hidden")}const M=document.getElementById("search-form"),$=document.getElementById("search-input"),O=document.getElementById("load-more");let c="",i=1,d=0;const w=15;a();M.addEventListener("submit",x);O.addEventListener("click",A);async function x(o){if(o.preventDefault(),c=$.value.trim(),!c){s.error({title:"Error",message:"Please enter a search term."});return}i=1,S(),a(),p();try{const e=await f(c,i);if(!e.hits||e.hits.length===0){s.info({title:"No results",message:"No images found."});return}d=e.totalHits,g(e.hits),d>i*w?L():(a(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.error(e),s.error({title:"Error",message:"Something went wrong."})}finally{b()}}async function A(){i+=1,p(),a();try{const o=await f(c,i);if(!o.hits||o.hits.length===0){s.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),a();return}g(o.hits),d>i*w?L():(a(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results."}));const e=document.querySelector(".gallery li");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch(o){console.error(o),s.error({title:"Error",message:"Something went wrong."})}finally{b()}}
//# sourceMappingURL=index.js.map
