import{a as w,S as v,i as s}from"./assets/vendor-CDCTPtxx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function e(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function u(r){if(r.ep)return;r.ep=!0;const n=e(r);fetch(r.href,n)}})();const E="52850733-d97c0fbc64eee6c455900e64a",S="https://pixabay.com/api/";async function m(o,t=1){try{return(await w.get(S,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(e){throw console.error("Pixabay API error:",e),e}}const f=document.querySelector(".gallery"),B=new v(".gallery a"),h=document.getElementById("loader"),y=document.getElementById("load-more");function g(o){const t=o.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function I(){f.innerHTML=""}function p(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function b(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}const q=document.getElementById("search-form"),P=document.getElementById("search-input"),M=document.getElementById("load-more");let i="",a=1,d=0;c();q.addEventListener("submit",x);M.addEventListener("click",$);async function x(o){if(o.preventDefault(),i=P.value.trim(),!i){s.error({title:"Error",message:"Please enter a search term."});return}a=1,I(),c(),p();try{const t=await m(i,a);if(!t.hits||t.hits.length===0){s.info({title:"No results",message:"No images found"});return}d=t.totalHits,g(t.hits),d>a*15&&b()}catch(t){console.error(t),s.error({title:"Error",message:"Something went wrong."})}finally{L()}}async function $(){a+=1,p(),c();try{const o=await m(i,a);if(!o.hits||o.hits.length===0){s.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}g([...document.querySelectorAll(".gallery li")].map(e=>({webformatURL:e.querySelector("img").src,largeImageURL:e.querySelector("a").href,tags:e.querySelector("img").alt,likes:e.querySelector("p").textContent.match(/Likes: (\d+)/)[1],views:e.querySelector("p").textContent.match(/Views: (\d+)/)[1]})),...o.hits),d>a*15?b():(s.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),c());const t=document.querySelector(".gallery li");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}catch(o){console.error(o),s.error({title:"Error",message:"Something went wrong."})}finally{L()}}
//# sourceMappingURL=index.js.map
